name: CI/CD PHP Apache (Local VM)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy ke Apache Local
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Permission Project
        run: |
          sudo chown -R www-data:www-data /var/www/html/myproject
          sudo chmod -R 755 /var/www/html/myproject

      - name: Deploy Code
        run: |
          cd /var/www/html/myproject
          git pull origin main

      - name: Reload Apache
        run: |
          sudo systemctl reload apache2
